[package]
name = "ragnarok_rebuild_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[features]
with-inspector = [
    "bevy-inspector-egui",
    "bevy_flycam",
    "iyes_perf_ui",
    "ragnarok_rebuild_bevy/debug",
]

[dependencies]
ragnarok_rebuild_common = { path = "../ragnarok_rebuild_common" }
ragnarok_rebuild_bevy = { path = "../ragnarok_rebuild_bevy" }

bevy = { workspace = true }
bevy-inspector-egui = { version = "0.25.2", optional = true }
bevy_flycam = { version = "0.14.1", optional = true }
iyes_perf_ui = { version = "0.3", optional = true }

tungstenite = { workspace = true }
url = { workspace = true }

serde = { workspace = true }
toml = { workspace = true }
